### ISSUE TITLE
Update dump() function. Save datetime itself instead of pointers in incident files

### ISSUE THREAD

**Issue by DiTsi** [DiTsi/impulse#140]
```
chain:
- datetime: &id001 2024-10-17 00:21:07.901147
  done: true
  identifier: Dmitry Tsybus
  result: 200
  type: user
- datetime: *id001
  done: true
  identifier: devops
  result: 200
  type: user_group
```

should be 

```
chain:
- datetime: 2024-10-17 00:21:07.901147
  done: true
  identifier: Dmitry Tsybus
  result: 200
  type: user
- datetime: 2024-10-17 00:21:07.901147
  done: true
  identifier: devops
  result: 200
  type: user_group
```
