### ISSUE TITLE
Update configuration structure to include new options

### ISSUE THREAD

**Issue by DiTsi** [DiTsi/impulse#148]
We need something like that to configure incidents behavior:
```yaml
incident:
  timeouts:
    firing: 60s
    unknown: 10s
    resolved: 10s
  recreate_chain_by_new_alerts: True
  update_status_notifications: True
  update_new_firing_notifications: True
  update_new_resolved_notifications: True
  take_it_notifications: True
```
