### ISSUE TITLE
Error handling request (no URI read)

### ISSUE THREAD

**Issue by autokilla47** [DiTsi/impulse#211]
Something went wrong?
I have 2 alerts with different 'dashboard_url':
Alert rule:
```
      - alert: ServiceDownv1
        expr: up == 0
        for: 2m
        labels:
          severity: critical
          alert_route_to_chat: impulse.rc
        annotations:
          summary: Service "{{ $labels.job }}" has been down for more than {{ .For }}
          description: Service "{{ $labels.job }}" has been down for more than {{ .For }}
          dashboard_url: "{{ $externalURL }}/dashboards"
          runbook: убедиться в отсутствии проблем с сетевой доступностью до {{ (or $labels.host $labels.instance) }}, проверить статус и логи основного объекта мониторинга

      - alert: ServiceDownv2
        expr: up == 0
        for: 2m
        labels:
          severity: critical
          alert_route_to_chat: impulse.rc
        annotations:
          summary: Service "{{ $labels.job }}" has been down for more than {{ .For }}
          description: Service "{{ $labels.job }}" has been down for more than {{ .For }}
          dashboard_url: "{{ $externalURL }}/d/vmagent?timezone=browser&var-env={{ $labels.env }}"
          runbook: убедиться в отсутствии проблем с сетевой доступностью до {{ (or $labels.host $labels.instance) }}, проверить статус и логи основного объекта мониторинга
```

And with ServiceDownv2 i have this in log:
```
impulse-1  | [2025-03-28 13:53:20 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:13)
impulse-1  | [2025-03-28 13:53:20 +0000] [13] [ERROR] Error handling request (no URI read)
impulse-1  | Traceback (most recent call last):
impulse-1  |   File "/usr/local/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
impulse-1  |     req = next(parser)
impulse-1  |           ^^^^^^^^^^^^
impulse-1  |   File "/usr/local/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
impulse-1  |     self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
impulse-1  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
impulse-1  |   File "/usr/local/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
impulse-1  |     super().__init__(cfg, unreader, peer_addr)
impulse-1  |   File "/usr/local/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
impulse-1  |     unused = self.parse(self.unreader)
impulse-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^
impulse-1  |   File "/usr/local/lib/python3.12/site-packages/gunicorn/http/message.py", line 271, in parse
impulse-1  |     self.get_data(unreader, buf, stop=True)
impulse-1  |   File "/usr/local/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
impulse-1  |     data = unreader.read()
impulse-1  |            ^^^^^^^^^^^^^^^
impulse-1  |   File "/usr/local/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
impulse-1  |     d = self.chunk()
impulse-1  |         ^^^^^^^^^^^^
impulse-1  |   File "/usr/local/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
impulse-1  |     return self.sock.recv(self.mxchunk)
impulse-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
impulse-1  |   File "/usr/local/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
impulse-1  |     sys.exit(1)
impulse-1  | SystemExit: 1
```

Alertmanager (v0.27.0) config:
```
global:
  resolve_timeout: 3m

route:
  receiver: blackhole
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 354m
  routes:
  - match_re:
      severity: fatal|critical|warning|info
    receiver: blackhole
    routes:
    - match_re:
        alert_route_to_chat: .*impulse.rc.*
      receiver: impulse

receivers:
- name: blackhole
- name: 'impulse'
  webhook_configs:
  - url: 'http://10.10.10.10:5000/'
```

Impulse config:
```
application:
  type: telegram
  impulse_address: https://10.10.10.10 # Due to Telegram's restrictions, only HTTPS is supported

  admin_users: ["Name"]
  users:
    Name: {id: 11111111}
  user_groups:
    test: {users: ["Name"]}
  channels:
    all_alerts: {id: -12323432432434}

route:
  channel: all_alerts
```
