### ISSUE TITLE
Unify configuration format for simple and other chain types

### ISSUE THREAD

**Issue by DiTsi** [DiTsi/impulse#237]
**Current behavior:**
In the configuration file, simple chains are defined as a list of steps, while `schedule` and `cloud` chains are defined as dictionaries.

```yaml
# simple
chains:
  simple_chain:
    - user: alice
    - wait: 10s

# schedule / cloud
chains:
  scheduled_chain:
    type: schedule
    steps:
      - user: bob
      - wait: 30s
```

**Problem:**
This inconsistency:
- Makes parsing more complex
- Breaks expectations for users switching between chain types
- Makes documentation and validation harder

Proposal:
Unify the format by requiring all chains to be defined as dictionaries with explicit type and steps fields.

Example (proposed unified format):
```yaml
chains:
  simple_chain:
    type: simple
    steps:
      - user: alice
      - wait: 10s

  scheduled_chain:
    type: schedule
    steps:
      - user: bob
      - wait: 30s
```
